export const search_cars = [
  {
    img: './car_model/ford.svg',
    brand: 'Ford Transit – 2021',
    description:'4.0 D5 PowerPulse Momentum 5dr AWD Geartronic Estate',
    mileage:'2500 Miles',
    fuel:'Diesel',
    transmission:'Manual',
    price:'$22,000',
  },
  {
    img: './car_model/glc.svg',
    brand: 'GLC – 2023',
    description:'4.0 D5 PowerPulse Momentum 5dr AWD Geartronic Estate',
    mileage:'50 Miles',
    fuel:'Petrol',
    transmission:'Automatic',
    price:'$95,000',
  },
  {
    img: './car_model/audi.svg',
    brand: 'Audi A6 3.5 – New',
    description:'3.5 D5 PowerPulse Momentum 5dr AWD Geartronic Estate',
    mileage:'100 Miles',
    fuel:'Petrol',
    transmission:'Automatic',
    price:'$58,000',
  },
  {
    img: './car_model/corola.svg',
    brand: 'Corolla Altis – 2023',
    description:'3.5 D5 PowerPulse Momentum 5dr AWD Geartronic Estate',
    mileage:'15000 Miles',
    fuel:'Petrol',
    transmission:'CVT',
    price:'$45,000',
  },
]